# Generated by Django 5.1.2 on 2024-12-23 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(auto_now=True)),
                ('delivery_person_name', models.CharField(max_length=100, null=True)),
                ('delivery_person_phone', models.CharField(max_length=15, null=True)),
                ('delivery_perdon_id', models.CharField(max_length=100, null=True)),
                ('delivery_person_id_image', models.TextField(null=True)),
                ('delivery_note_image', models.TextField(null=True)),
                ('status', models.CharField(choices=[('in-transit', 'in-transit'), ('delivered', 'delivered'), ('returned', 'returned')], max_length=200)),
                ('paid_status', models.CharField(choices=[('paid & delivered', 'paid & delivered'), ('paid & not delivered', 'paid & not delivered'), ('not paid & delivered', 'not paid & delivered'), ('not paid & not delivered', 'not paid & not delivered')], max_length=200)),
                ('last_updates', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Details',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='OrgDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('payment', models.TextField()),
                ('terms', models.TextField()),
                ('logo', models.ImageField(default='', upload_to='org_pics')),
            ],
            options={
                'verbose_name_plural': 'Org Details',
            },
        ),
        migrations.CreateModel(
            name='StoreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=16.0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('cart', 'cart'), ('ínvoiced', 'invoiced'), ('sold', 'sold'), ('returned', 'returned'), ('delivered', 'delivered'), ('Sold & Delivered', 'Sold & Delivered')], max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productbuild')),
            ],
            options={
                'verbose_name_plural': 'Store Sales',
            },
        ),
        migrations.CreateModel(
            name='StoreOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.customerdetails')),
                ('delivery_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.deliverydetails')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.storesales')),
            ],
            options={
                'verbose_name_plural': 'Store Orders',
            },
        ),
    ]
