# Generated by Django 5.1 on 2024-10-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesales',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('sold', 'sold'), ('returned', 'returned'), ('delivered', 'delivered')], max_length=200),
        ),
    ]
