# Generated by Django 5.1.2 on 2025-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_filetransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesales',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('ínvoiced', 'invoiced'), ('sold', 'sold'), ('in-stock', 'in-stock'), ('returned', 'returned'), ('delivered', 'delivered'), ('Sold & Delivered', 'Sold & Delivered')], max_length=200),
        ),
    ]
