# Generated by Django 5.1.2 on 2024-11-01 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_customerdetails_orgdetails_alter_storesales_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdetails',
            options={'verbose_name_plural': 'Customer Details'},
        ),
        migrations.AlterModelOptions(
            name='storeorders',
            options={'verbose_name_plural': 'Store Orders'},
        ),
        migrations.AddField(
            model_name='storeorders',
            name='customer_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.customerdetails'),
        ),
    ]
