# Generated by Django 5.1.2 on 2024-11-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_customerdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorders',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesales',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('ínvoiced', 'invoiced'), ('sold', 'sold'), ('returned', 'returned'), ('delivered', 'delivered'), ('Sold & Delivered', 'Sold & Delivered')], max_length=200),
        ),
    ]
