# Generated by Django 5.1.2 on 2025-04-07 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_orgdetails_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdetails',
            name='seller',
        ),
        migrations.AddField(
            model_name='orgdetails',
            name='seller',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
