# Generated by Django 5.1.2 on 2024-11-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_storeorders_delivery_cost_alter_storesales_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateField(auto_now=True)),
                ('delivery_person_name', models.CharField(max_length=100, null=True)),
                ('delivery_person_phone', models.CharField(max_length=15, null=True)),
                ('delivery_perdon_id', models.CharField(max_length=100, null=True)),
                ('delivery_person_id_image', models.TextField(null=True)),
                ('delivery_note_image', models.TextField(null=True)),
                ('status', models.CharField(choices=[('in-transit', 'in-transit'), ('delivered', 'delivered'), ('returned', 'returned')], max_length=200)),
                ('paid_status', models.CharField(choices=[('paid & delivered', 'paid & delivered'), ('paid & not delivered', 'paid & not delivered'), ('not paid & delivered', 'not paid & delivered'), ('not paid & not delivered', 'not paid & not delivered')], max_length=200)),
                ('last_updates', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Details',
            },
        ),
        migrations.RemoveField(
            model_name='storeorders',
            name='delivery_cost',
        ),
        migrations.AddField(
            model_name='storeorders',
            name='delivery_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.deliverydetails'),
        ),
    ]
