# Generated by Django 5.1.2 on 2024-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_deliverydetails_remove_storeorders_delivery_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
