# Generated by Django 5.1 on 2024-10-18 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specifications', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Product Features',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='products_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Models',
            },
        ),
        migrations.CreateModel(
            name='ProductOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product Origin',
            },
        ),
        migrations.CreateModel(
            name='ProductBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial1', models.CharField(max_length=100)),
                ('serial2', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('was', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('in-stock', 'in-stock'), ('out-stock', 'out-stock'), ('low', 'low')], max_length=200)),
                ('overview', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productbrand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productcategory')),
                ('features', models.ManyToManyField(to='ecommerce.productfeatures')),
                ('images', models.ManyToManyField(to='ecommerce.productimages')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productmodel')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productorigin')),
            ],
            options={
                'verbose_name_plural': 'Create Product',
            },
        ),
    ]
