# Generated by Django 5.1.2 on 2024-12-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(blank=True, max_length=100, null=True)),
                ('decsription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Generation',
            },
        ),
        migrations.CreateModel(
            name='ProductMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('decsription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Price Range',
            },
        ),
        migrations.CreateModel(
            name='ProductProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('decsription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Processor',
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('decscription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Sub Category',
            },
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='productimages',
            name='tag_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productbuild',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productgeneration'),
        ),
        migrations.AddField(
            model_name='productbuild',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productmemory'),
        ),
        migrations.AddField(
            model_name='productbuild',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productprocessor'),
        ),
        migrations.AddField(
            model_name='productbuild',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.productsubcategory'),
        ),
    ]
