# Generated by Django 5.1.2 on 2024-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Categories',
            },
        ),
    ]
