# Generated by Django 5.1 on 2024-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productbrand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='products_pics'),
        ),
    ]
