# Generated by Django 5.1.2 on 2025-01-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_deliverycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='customer_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='delivery',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='faqs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orgprofile',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
