# Generated by Django 5.1.2 on 2025-01-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_orgprofile_about_orgprofile_customer_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='ig_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='pi_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='th_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='wa_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orgprofile',
            name='x_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
