# Generated by Django 5.1.2 on 2025-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_productbuild_disty_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbuild',
            name='designation',
            field=models.CharField(choices=[('All', 'All'), ('Ecommerce', 'Ecommerce'), ('Store', 'Store')], default='All', max_length=20, null=True),
        ),
    ]
